name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up AWS credentials using secrets
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2  # Set your region

    # Step 3: Set up kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        kubectl-version: 'v1.24.0'  # Optional, specify the kubectl version

    # Step 4: Update kubeconfig for EKS
    - name: Update kubeconfig for EKS
      run: |
        aws eks --region us-east-2 update-kubeconfig --name codets

    # Step 5: Apply Kubernetes resources (deployment and service)
    - name: Deploy to Kubernetes (EKS)
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
